/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import controller.BarangKeluarController;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import model.Barang;
import model.ComboItem;
import model.Transaksi;

/**
 *
 * @author T450
 */
public class FormBrgKeluar extends javax.swing.JFrame {
    private static ComboItem[] dataBarang = new ComboItem[] {  };
    private static DefaultComboBoxModel<ComboItem> modelBarang = new DefaultComboBoxModel<>(dataBarang);
    
    BarangKeluarController services = new BarangKeluarController();
    /**
     * Creates new form FormBarang
     */
    public FormBrgKeluar() {
        initComponents();
        
        comboBarang.setModel(modelBarang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputTanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Simpan = new javax.swing.JButton();
        Tutup = new javax.swing.JButton();
        inputJumlah = new javax.swing.JSpinner();
        comboBarang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Tambah Barang"));

        jLabel1.setText("Tanggal *");

        inputTanggal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputTanggalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputTanggalFocusLost(evt);
            }
        });

        jLabel2.setText("Nama Barang *");

        jLabel3.setText("Jumlah Barang Keluar *");

        Simpan.setText("Simpan");
        Simpan.setPreferredSize(new java.awt.Dimension(63, 28));
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Tutup.setText("Tutup");
        Tutup.setPreferredSize(new java.awt.Dimension(63, 28));
        Tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputJumlah)
                    .addComponent(inputTanggal)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(Tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutupActionPerformed
        this.dispose();
        clear();
    }//GEN-LAST:event_TutupActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        ComboItem barang = (ComboItem) comboBarang.getSelectedItem();
        String tanggal = inputTanggal.getText();
        int jumlah = (int) inputJumlah.getValue();
        int idBarang = barang.getValue();
        
        boolean verified =  verify(tanggal, jumlah);
        
        if(verified) {
            Transaksi data = new Transaksi();
            
            data.idBarang = idBarang;
            data.jumlah = jumlah;
            data.tanggal = tanggal;
            
            services.addData(data);
            services.updateJumlah(data.idBarang, data.jumlah, true);
            services.getData();
            
            this.dispose();
            clear();
        }
    }//GEN-LAST:event_SimpanActionPerformed

    private void inputTanggalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTanggalFocusGained
        if (inputTanggal.getText().equals("dd-mm-yyyy")) {
            inputTanggal.setText("");
        }
    }//GEN-LAST:event_inputTanggalFocusGained

    private void inputTanggalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTanggalFocusLost
         if (inputTanggal.getText().equals("")) {
            inputTanggal.setText("dd-mm-yyyy");
        }
    }//GEN-LAST:event_inputTanggalFocusLost
    
    public boolean verify(String tanggal, int jumlah) {
        boolean verified = true;
        
        Border customBorder = new LineBorder(Color.RED, 1, true);
        Border normal = new LineBorder(Color.GRAY, 1, true);
        
        SimpleDateFormat inputDateFormat = new SimpleDateFormat("dd-MM-yyy");
        Date parsed = null;
        
        try {
            parsed = inputDateFormat.parse(tanggal);
         } catch (ParseException e) {
            System.err.println("Tanggal salah: " + e.getMessage());
        }
        
        if(parsed == null) {
            inputTanggal.setBorder(customBorder);
            verified = false;
        } else {
            inputTanggal.setBorder(normal);
        }
        
        if(jumlah < 1) {
            inputTanggal.setBorder(customBorder);
            verified = false;
        } else {
            inputTanggal.setBorder(normal);
        }
        
        return verified;
    }
    
    
    public void setView() {
        this.setLocation(220, 70);
        this.setVisible(true);
    }
    
    public void setBarang(List<Barang> data) {
        modelBarang.removeAllElements();
        for(Barang x : data) {
            modelBarang.addElement(new ComboItem(x.nama, x.id));
        }
    }
    
    private void clear() {
        inputTanggal.setText("");
        inputJumlah.setValue(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBrgKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBrgKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBrgKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBrgKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBrgKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Tutup;
    private javax.swing.JComboBox<ComboItem> comboBarang;
    private javax.swing.JSpinner inputJumlah;
    private javax.swing.JTextField inputTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
