/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import controller.BarangController;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.ComboItem;
import model.Jenis;
import model.Satuan;
import java.awt.Color;
import javax.swing.border.LineBorder;
import javax.swing.border.Border;
import model.Barang;

/**
 *
 * @author T450
 */
public class FormBarang extends javax.swing.JFrame {
    private static ComboItem[] dataJenis = new ComboItem[] {  };
    private static ComboItem[] dataSatuan = new ComboItem[] {  };
    
    private static DefaultComboBoxModel<ComboItem> modelJenis = new DefaultComboBoxModel<>(dataJenis);
    private static DefaultComboBoxModel<ComboItem> modelSatuan = new DefaultComboBoxModel<>(dataSatuan);
    
    BarangController services = new BarangController();
    private static int editId = 0;
    /**
     * Creates new form FormBarang
     */
    public FormBarang() {
        initComponents();
        
        comboJenis.setModel(modelJenis);
        comboSatuan.setModel(modelSatuan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboJenis = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Simpan = new javax.swing.JButton();
        Tutup = new javax.swing.JButton();
        comboSatuan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        inputStok = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Tambah Barang"));

        labelNama.setText("Nama Barang *");

        jLabel2.setText("Jenis Barang *");

        jLabel3.setText("Satuan *");

        Simpan.setText("Simpan");
        Simpan.setPreferredSize(new java.awt.Dimension(63, 28));
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Tutup.setText("Tutup");
        Tutup.setPreferredSize(new java.awt.Dimension(63, 28));
        Tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutupActionPerformed(evt);
            }
        });

        jLabel4.setText("Stok *");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputStok)
                    .addComponent(inputNama)
                    .addComponent(comboJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(Tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboSatuan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNama)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutupActionPerformed
        this.dispose();
        clear();
    }//GEN-LAST:event_TutupActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        String nama = inputNama.getText();
        ComboItem jenis = (ComboItem) comboJenis.getSelectedItem();
        int  stok = (int) inputStok.getValue();
        ComboItem satuan = (ComboItem) comboSatuan.getSelectedItem();
       
        boolean verified = verify(nama, stok);
        
        if(verified) {
            Barang data = new Barang();
            
            data.id = editId;
            data.nama = nama;
            data.idJenis = jenis.getValue();
            data.stok = stok;
            data.idSatuan = satuan.getValue();

            if(editId > 0) {
                services.editData(data);
                editId = 0;
            } else {
                services.addData(data);
            }

            services.getData();

            this.dispose();
            clear();
        }
    }//GEN-LAST:event_SimpanActionPerformed
    
    public boolean verify(String nama, int stok) {
        boolean verified = true;
        
        Border customBorder = new LineBorder(Color.RED, 1, true);
        Border normal = new LineBorder(Color.GRAY, 1, true);
        
        if(nama.isEmpty()) {
            inputNama.setBorder(customBorder);
            verified = false;
        } else {
            inputNama.setBorder(normal);
        }
        
        if(stok < 1) {
            inputStok.setBorder(customBorder);
            verified = false;
        } else {
            inputStok.setBorder(normal);
        }
        
        return verified;
    }
    
    public void clear() {
        inputNama.setText("");
        comboJenis.setSelectedIndex(0);
        inputStok.setValue(0);
        comboSatuan.setSelectedIndex(0);
    }
    
    public void setView() {
        this.setLocation(220, 70);
        this.setVisible(true);
        editId = 0;
    }
    
    public void setEdit(int id) {
        services.getDataById(id);
    }
    
    public void setJenis(List<Jenis> data) {
        modelJenis.removeAllElements();
        for(Jenis x : data) {
            modelJenis.addElement(new ComboItem(x.nama, x.id));
        }
    }
    
     public void setSatuan(List<Satuan> data) {
         modelSatuan.removeAllElements();
        for(Satuan x : data) {
            modelSatuan.addElement(new ComboItem(x.nama, x.id));
        }
    }
     
     public void setForm(Barang data) {
         inputNama.setText(data.nama);
         inputStok.setValue(data.stok);        
         editId = data.id;
         
        for(int i = 0; i < modelJenis.getSize(); i++) {
           ComboItem x = modelJenis.getElementAt(i);
           if(x.getValue() == data.idJenis) {
               modelJenis.setSelectedItem(x);
               break;
           }
        }

        for(int i = 0; i < modelSatuan.getSize(); i++) {
           ComboItem x = modelSatuan.getElementAt(i);
           if(x.getValue() == data.idJenis) {
               modelSatuan.setSelectedItem(x);
               break;
           }
        }
         
        this.setLocation(220, 70);
        this.setVisible(true);
     }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBarang().setVisible(true);
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Tutup;
    private javax.swing.JComboBox<ComboItem> comboJenis;
    private javax.swing.JComboBox<ComboItem> comboSatuan;
    private javax.swing.JTextField inputNama;
    private javax.swing.JSpinner inputStok;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelNama;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
