/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;

/**
 *
 * @author Acer
 */
public class Template extends javax.swing.JFrame {
    private static Login login = new Login();
    private static Dashboard dashboard = new Dashboard();
    private static DataBarang dataBarang = new DataBarang();
    private static JenisBarang jenisBarang = new JenisBarang();
    private static SatuanBarang satuanBarang = new SatuanBarang();
    private static BarangMasuk barangMasuk = new BarangMasuk();
    private static BarangKeluar barangKeluar = new BarangKeluar();
    
    private static String roles;
    /**
     * Creates new form Dashboard
     */
    public Template() {
        initComponents();
//        
//        dashboard.setView();
//        mainFrame.add(dashboard);
        //menuDashActionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "constructorEvent"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        mainFrame = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuDash = new javax.swing.JMenuItem();
        menuKeluar = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuBarang = new javax.swing.JMenuItem();
        menuJenis = new javax.swing.JMenuItem();
        menuSatuan = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuBrgMasuk = new javax.swing.JMenuItem();
        menuBrgKeluar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout mainFrameLayout = new javax.swing.GroupLayout(mainFrame);
        mainFrame.setLayout(mainFrameLayout);
        mainFrameLayout.setHorizontalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        mainFrameLayout.setVerticalGroup(
            mainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        menuHome.setText("  Home  ");
        menuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHomeActionPerformed(evt);
            }
        });

        menuDash.setText("  Dashboard  ");
        menuDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDashActionPerformed(evt);
            }
        });
        menuHome.add(menuDash);

        menuKeluar.setText("  Keluar  ");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        menuHome.add(menuKeluar);

        menuBar.add(menuHome);

        menuMaster.setText("  Data Master  ");

        menuBarang.setText("  Data Barang  ");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        menuMaster.add(menuBarang);

        menuJenis.setText("  Jenis Barang  ");
        menuJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJenisActionPerformed(evt);
            }
        });
        menuMaster.add(menuJenis);

        menuSatuan.setText("  Satuan  ");
        menuSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSatuanActionPerformed(evt);
            }
        });
        menuMaster.add(menuSatuan);

        menuBar.add(menuMaster);

        menuTransaksi.setText("  Transaksi  ");

        menuBrgMasuk.setText("  Barang Masuk  ");
        menuBrgMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBrgMasukActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuBrgMasuk);

        menuBrgKeluar.setText("  Barang Keluar  ");
        menuBrgKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBrgKeluarActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuBrgKeluar);

        menuBar.add(menuTransaksi);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        BarangController service = new BarangController();
        
        service.getData();
        
        mainFrame.removeAll();
        dataBarang.setView();
        mainFrame.add(dataBarang);
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJenisActionPerformed
         JenisController service = new JenisController();
        
        service.getData();
        
        mainFrame.removeAll();
        jenisBarang.setView();
        mainFrame.add(jenisBarang);
    }//GEN-LAST:event_menuJenisActionPerformed

    private void menuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHomeActionPerformed
           //Home
    }//GEN-LAST:event_menuHomeActionPerformed

    private void menuDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDashActionPerformed
        DashboardController services = new DashboardController();
        String jmlBarang = services.getBarang();
        String jmlMasuk = services.getMasuk();
        String jmlKeluar = services.getKeluar();
        String jmlUser = services.getUser();
        
        services.getData();
        
        dashboard.setBarang(jmlBarang);
        dashboard.setMasuk(jmlMasuk);
        dashboard.setKeluar(jmlKeluar);
        dashboard.setUser(jmlUser);
        
        mainFrame.removeAll();
        dashboard.setView();
        mainFrame.add(dashboard);
        
        this.setVisible(true);
    }//GEN-LAST:event_menuDashActionPerformed

    private void menuSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSatuanActionPerformed
        SatuanController service = new SatuanController();
        
        service.getData();
        
        mainFrame.removeAll();
        satuanBarang.setView();
        mainFrame.add(satuanBarang);
    }//GEN-LAST:event_menuSatuanActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void menuBrgMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBrgMasukActionPerformed
        BarangMasukController service = new BarangMasukController();
        
        service.getData();
        
        mainFrame.removeAll();
        barangMasuk.setView();
        mainFrame.add(barangMasuk);
    }//GEN-LAST:event_menuBrgMasukActionPerformed

    private void menuBrgKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBrgKeluarActionPerformed
        BarangKeluarController service = new BarangKeluarController();
        
        service.getData();
        
        mainFrame.removeAll();
        barangKeluar.setView();
        mainFrame.add(barangKeluar);
    }//GEN-LAST:event_menuBrgKeluarActionPerformed
    
    public void setView(String roles) {
        DashboardController services = new DashboardController();
        String jmlBarang = services.getBarang();
        String jmlMasuk = services.getMasuk();
        String jmlKeluar = services.getKeluar();
        String jmlUser = services.getUser();
        
        services.getData();
        
        dashboard.setBarang(jmlBarang);
        dashboard.setMasuk(jmlMasuk);
        dashboard.setKeluar(jmlKeluar);
        dashboard.setUser(jmlUser);
        
        mainFrame.removeAll();
        dashboard.setView();
        mainFrame.add(dashboard);
        
        if(null != roles) switch (roles) {
            case "administrator":
                menuMaster.setVisible(true);
                menuTransaksi.setVisible(true);
                break;
            case "admin-transaksi":
                menuMaster.setVisible(false);
                menuTransaksi.setVisible(true);
                break;
            case "admin-barang":
                menuMaster.setVisible(true);
                menuTransaksi.setVisible(false);
                break;
            default:
                break;
        }
        
        this.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Template().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane mainFrame;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuBrgKeluar;
    private javax.swing.JMenuItem menuBrgMasuk;
    private javax.swing.JMenuItem menuDash;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menuJenis;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuSatuan;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
